table AnalyticsFactMetricSplSundaybloomMetrics
	lineageTag: 21aac922-8560-40af-8a0c-8cc836314ae7

	column CityName
		dataType: string
		lineageTag: ba0a5dfa-84a1-4613-bd9b-22782296d0bc
		summarizeBy: none
		sourceColumn: CityName

		annotation SummarizationSetBy = Automatic

	column MetricValueDateTime
		dataType: dateTime
		formatString: Long Date
		lineageTag: a73f8de9-f9e0-4856-9bda-e70ea4b9c202
		summarizeBy: none
		sourceColumn: MetricValueDateTime

		variation Variation
			isDefault
			relationship: 60c4aa2a-6fa1-4255-8f6f-fba060b3eb28
			defaultHierarchy: LocalDateTable_3933fc9d-df54-4782-bab1-3b4670fa619a.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column CampusName
		dataType: string
		lineageTag: 92d38f22-12e3-47be-9a3b-9f609ae6b020
		summarizeBy: none
		sourceColumn: CampusName

		annotation SummarizationSetBy = Automatic

	column ScheduleName
		dataType: string
		lineageTag: 03cfd7b2-9ee4-4a5f-ae60-6c0e44ea46d7
		summarizeBy: none
		sourceColumn: ScheduleName

		annotation SummarizationSetBy = Automatic

	column Count
		dataType: double
		lineageTag: 73d31686-3b25-4a54-bf3f-48274c697ccb
		summarizeBy: sum
		sourceColumn: Count

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Literal
		dataType: string
		lineageTag: d10da83e-de70-4044-afb7-f7fe1a2be533
		summarizeBy: none
		sourceColumn: Literal

		annotation SummarizationSetBy = Automatic

	column EventName
		dataType: string
		lineageTag: 36ff992e-dae5-4239-8e79-07f5078b6d4e
		summarizeBy: none
		sourceColumn: EventName

		annotation SummarizationSetBy = Automatic

	partition AnalyticsFactMetricSplSundaybloomMetrics = m
		mode: import
		source =
				let
				    Source = PowerBI.Dataflows(null),
				#"589387ad-ce92-442a-b77f-3eb4eb51443d" = Source{[workspaceId="589387ad-ce92-442a-b77f-3eb4eb51443d"]}[Data],
				#"ea17ab7e-1ce3-4cc9-bc6f-bb7507b0c3fa" = #"589387ad-ce92-442a-b77f-3eb4eb51443d"{[dataflowId="ea17ab7e-1ce3-4cc9-bc6f-bb7507b0c3fa"]}[Data],
				dbo_AnalyticsFactMetricSpecialSundaysbloom = #"ea17ab7e-1ce3-4cc9-bc6f-bb7507b0c3fa"{[entity="AnalyticsFactMetricSpecialSundaysbloom"]}[Data],
				    #"Filtered Rows" = Table.SelectRows(dbo_AnalyticsFactMetricSpecialSundaysbloom, each true),
				    #"Grouped Rows" = Table.Group(#"Filtered Rows", {"CityName", "MetricValueDateTime", "CampusName", "ScheduleName","EventName"}, {{"Count", each List.Sum([YValue]), type nullable number}}),
				    #"Inserted Literal" = Table.AddColumn(#"Grouped Rows", "Literal", each "bloom", type text)
				in
				    #"Inserted Literal"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

