table AnalyticsFactMetricSplSundayGatheringAttMetrics
	lineageTag: 5b4dbe6a-1bea-4609-a995-261faf88dfd3

	column CityName
		dataType: string
		lineageTag: 694b683c-8b2d-4118-b15a-00aa97b07a7b
		summarizeBy: none
		sourceColumn: CityName

		annotation SummarizationSetBy = Automatic

	column MetricValueDateTime
		dataType: dateTime
		formatString: Long Date
		lineageTag: 1103c7c9-fd7d-4389-a72c-a79756b431e2
		summarizeBy: none
		sourceColumn: MetricValueDateTime

		variation Variation
			isDefault
			relationship: 318265da-6bb5-4e5a-b8a9-b6d63bdbd00d
			defaultHierarchy: LocalDateTable_c0addfdd-e60c-42be-9458-6e3a08786bed.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column CampusName
		dataType: string
		lineageTag: 9af25545-40ba-4d2a-897a-4d81c97f4467
		summarizeBy: none
		sourceColumn: CampusName

		annotation SummarizationSetBy = Automatic

	column ScheduleName
		dataType: string
		lineageTag: c675bb07-34a0-4554-8344-a9204f6a7975
		summarizeBy: none
		sourceColumn: ScheduleName

		annotation SummarizationSetBy = Automatic

	column Count
		dataType: double
		lineageTag: 1aa91f49-d8f0-4e2a-91f1-4b6527b93000
		summarizeBy: sum
		sourceColumn: Count

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Literal
		dataType: string
		lineageTag: fe152f1a-5f29-4705-a140-58e915fcbd86
		summarizeBy: none
		sourceColumn: Literal

		annotation SummarizationSetBy = Automatic

	column EventName
		dataType: string
		lineageTag: 68db18e2-a259-4b0c-a808-6e1bdbfd5133
		summarizeBy: none
		sourceColumn: EventName

		annotation SummarizationSetBy = Automatic

	partition AnalyticsFactMetricSplSundayGatheringAttMetrics = m
		mode: import
		source =
				let
				    Source = PowerBI.Dataflows(null),
				#"589387ad-ce92-442a-b77f-3eb4eb51443d" = Source{[workspaceId="589387ad-ce92-442a-b77f-3eb4eb51443d"]}[Data],
				#"ea17ab7e-1ce3-4cc9-bc6f-bb7507b0c3fa" = #"589387ad-ce92-442a-b77f-3eb4eb51443d"{[dataflowId="ea17ab7e-1ce3-4cc9-bc6f-bb7507b0c3fa"]}[Data],
				dbo_AnalyticsFactMetricSpecialSundaysGatheringAttendance = #"ea17ab7e-1ce3-4cc9-bc6f-bb7507b0c3fa"{[entity="AnalyticsFactMetricSpecialSundaysGatheringAttendance"]}[Data],
				    #"Filtered Rows" = Table.SelectRows(dbo_AnalyticsFactMetricSpecialSundaysGatheringAttendance, each true),
				    #"Grouped Rows" = Table.Group(#"Filtered Rows", {"CityName", "MetricValueDateTime", "CampusName", "ScheduleName","EventName"}, {{"Count", each List.Sum([YValue]), type nullable number}}),
				    #"Inserted Literal" = Table.AddColumn(#"Grouped Rows", "Literal", each "Adults", type text)
				in
				    #"Inserted Literal"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

