create or alter view [dbo].[BQ_Person_Incremental] as 
SELECT
    p.Id,
    CASE WHEN p.IsSystem = 1 THEN 'true' WHEN p.IsSystem = 0 THEN 'false' ELSE NULL END AS IsSystem,
    p.RecordTypeValueId,
    p.RecordStatusValueId,
    p.RecordStatusReasonValueId,
    p.ConnectionStatusValueId,
    CASE WHEN p.IsDeceased = 1 THEN 'true' WHEN p.IsDeceased = 0 THEN 'false' ELSE NULL END AS IsDeceased,
    p.TitleValueId,
    p.FirstName,
    p.NickName,
    p.MiddleName,
    p.LastName,
    p.SuffixValueId,
    p.PhotoId,
    p.BirthDay,
    p.BirthMonth,
    p.BirthYear,
    p.Gender,
    p.MaritalStatusValueId,
    CONVERT(varchar(10), p.AnniversaryDate, 23) AS AnniversaryDate,
    p.GivingGroupId,
    p.Email,
    CASE WHEN p.IsEmailActive = 1 THEN 'true' WHEN p.IsEmailActive = 0 THEN 'false' ELSE NULL END AS IsEmailActive,
    p.EmailNote,
    p.SystemNote,
    p.ViewedCount,
    CAST(p.Guid AS nvarchar(36)) AS Guid,
    CONVERT(varchar(23), p.CreatedDateTime, 126) AS CreatedDateTime,
    CONVERT(varchar(23), p.ModifiedDateTime, 126) AS ModifiedDateTime,
    p.CreatedByPersonAliasId,
    p.ModifiedByPersonAliasId,
    p.EmailPreference,
    p.InactiveReasonNote,
    p.ForeignKey,
    CAST(p.ReviewReasonValueId AS nvarchar(20)) AS ReviewReasonValueId,
    p.ReviewReasonNote,
    p.GraduationYear,
    CAST(p.ForeignGuid AS nvarchar(36)) AS ForeignGuid,
    p.ForeignId,
    CONVERT(varchar(23), p.RecordStatusLastModifiedDateTime, 126) AS RecordStatusLastModifiedDateTime,
    p.CommunicationPreference,
    p.TopSignalColor,
    p.TopSignalIconCssClass,
    p.TopSignalId,
    p.AgeClassification,
    p.PrimaryFamilyId,
    p.DaysUntilAnniversary,
    CASE WHEN p.IsLockedAsChild = 1 THEN 'true' WHEN p.IsLockedAsChild = 0 THEN 'false' ELSE NULL END AS IsLockedAsChild,
    CONVERT(varchar(23), p.DeceasedDate, 126) AS DeceasedDate,
    p.GivingLeaderId,
    CONVERT(varchar(10), p.BirthDate, 23) AS BirthDate,
    CAST(p.ContributionFinancialAccountId AS nvarchar(20)) AS ContributionFinancialAccountId,
    p.PrimaryCampusId,
    p.GivingId,
    CAST(p.PreferredLanguageValueId AS nvarchar(20)) AS PreferredLanguageValueId,
    p.AccountProtectionProfile,
    p.DaysUntilBirthday,
    p.ReminderCount,
    p.RaceValueId,
    p.EthnicityValueId,
    p.BirthDateKey,
    p.AgeBracket,
    p.Age,
    p.FirstNamePronunciationOverride,
    p.NickNamePronunciationOverride,
    p.LastNamePronunciationOverride,
    p.PronunciationNote,
    p.PrimaryAliasId,
    CAST(p.PrimaryAliasGuid AS nvarchar(36)) AS PrimaryAliasGuid,
    CASE WHEN p.IsChatProfilePublic = 1 THEN 'true' WHEN p.IsChatProfilePublic = 0 THEN 'false' ELSE NULL END AS IsChatProfilePublic,
    CASE WHEN p.IsChatOpenDirectMessageAllowed = 1 THEN 'true' WHEN p.IsChatOpenDirectMessageAllowed = 0 THEN 'false' ELSE NULL END AS IsChatOpenDirectMessageAllowed,
    p.RecordSourceValueId,
    CONVERT(varchar(23), CURRENT_TIMESTAMP, 126) AS _loaded_at,
    'rock_rms' AS _source_system
FROM person p
WHERE p.ModifiedDateTime >= (
        SELECT TOP(1) Last_Generated_Time
        FROM scheduler_log
        WHERE View_Name = 'BQ_Person_Incremental'
        ORDER BY Last_Generated_Time DESC
      )
  AND p.ModifiedDateTime <= CURRENT_TIMESTAMP


-- select column_name, data_type
-- from information_schema.columns
-- where table_name = 'BQ_Person_Incremental'